// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCym_e_HRaGcy389eQPdZhItMYJK-w_1Sc',
    appId: '1:212239808610:web:4f36e058474a92e74df93b',
    messagingSenderId: '212239808610',
    projectId: 'the-durga-app',
    authDomain: 'the-durga-app.firebaseapp.com',
    storageBucket: 'the-durga-app.firebasestorage.app',
    measurementId: 'G-4G4QY4K4EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmQdViJVbJcWyAAEwcwVDTpWfGqE7RvnY',
    appId: '1:212239808610:android:49a402b2c6884cb24df93b',
    messagingSenderId: '212239808610',
    projectId: 'the-durga-app',
    storageBucket: 'the-durga-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARJJcnfgV7rtaShwX6CoLgFr51VqY40oI',
    appId: '1:212239808610:ios:6ba2dfc82f87c0c44df93b',
    messagingSenderId: '212239808610',
    projectId: 'the-durga-app',
    storageBucket: 'the-durga-app.firebasestorage.app',
    iosBundleId: 'com.example.durga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARJJcnfgV7rtaShwX6CoLgFr51VqY40oI',
    appId: '1:212239808610:ios:6ba2dfc82f87c0c44df93b',
    messagingSenderId: '212239808610',
    projectId: 'the-durga-app',
    storageBucket: 'the-durga-app.firebasestorage.app',
    iosBundleId: 'com.example.durga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCym_e_HRaGcy389eQPdZhItMYJK-w_1Sc',
    appId: '1:212239808610:web:1add3a1dac2aea5f4df93b',
    messagingSenderId: '212239808610',
    projectId: 'the-durga-app',
    authDomain: 'the-durga-app.firebaseapp.com',
    storageBucket: 'the-durga-app.firebasestorage.app',
    measurementId: 'G-B7TNGR6P9Z',
  );
}
